### ISSUE TITLE
version 0.8 Rename Uploaded File fails

### ISSUE THREAD

**Issue by vnt** [davidyell/CakePHP3-Proffer#214] opened 2017-01-21 10:15 UTC
version 0.8 brakes image upload

Warning (2): rename(,/Users/vnt/Sites/jc/webroot/files/stores/logo/e923986a-7422-4543-b6e8-7554c08ab616/salumi-toscani.jpg): No such file or directory [ROOT/vendor/davidyell/proffer/src/Model/Behavior/ProfferBehavior.php, line 271]
Code Context

        }

        return rename($file, $destination);

$file = null
$destination = '/Users/vnt/Sites/jc/webroot/files/stores/logo/e923986a-7422-4543-b6e8-7554c08ab616/salumi-toscani-Dollarphotoclub_49081892.jpg'

rename - [internal], line ??
Proffer\Model\Behavior\ProfferBehavior::moveUploadedFile() - ROOT/vendor/davidyell/proffer/src/Model/Behavior/ProfferBehavior.php, line 271
Proffer\Model\Behavior\ProfferBehavior::process() - ROOT/vendor/davidyell/proffer/src/Model/Behavior/ProfferBehavior.php, line 138
Proffer\Model\Behavior\ProfferBehavior::beforeSave() - ROOT/vendor/davidyell/proffer/src/Model/Behavior/ProfferBehavior.php, line 87
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 426
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 391
Cake\ORM\Table::dispatchEvent() - CORE/src/Event/EventDispatcherTrait.php, line 78
Cake\ORM\Table::_processSave() - CORE/src/ORM/Table.php, line 1543
Cake\ORM\Table::Cake\ORM\{closure}() - CORE/src/ORM/Table.php, line 1492
Cake\Database\Connection::transactional() - CORE/src/Database/Connection.php, line 570
Cake\ORM\Table::save() - CORE/src/ORM/Table.php, line 1493
Manager\Controller\StoresController::edit() - ROOT/plugins/Manager/src/Controller/StoresController.php, line 132
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 121
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 95
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 60

**Comment by davidyell** [comment] 2017-01-23 10:39
Duplicate of #211

**Closed by davidyell** 2017-01-23 10:39 UTC
