### ISSUE TITLE
Upload creating an exception

### ISSUE THREAD

**Issue by spacebiscuit** [davidyell/CakePHP3-Proffer#239] opened 2017-07-24 20:38 UTC
Hi - I raised this issue a few weeks back in the Cake IRC chat room but have only got got around to posting the details of the issue. In short, I have a model called Links, which has a single file stored in the 'links' table.

My LinksTable.php:

```php
<?= $this->Form->create($link, ['type' => 'file', 'class' => 'form-horizontal form-label-left']) ?>

    <?php
    echo $this->Form->input('title', ['placeholder' => '']);
    echo $this->Form->input('address', ['placeholder' => '']);
    echo $this->Form->input('active', ['placeholder' => '', 'options' => [false => 'No', true => 'Yes']]);
    ?>

    <?php 
    if(isset($link->link_images)){
        foreach ($link->link_images as $key => $image): ?>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Image</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php echo $this->Html->image('linkimages/link_image/'.$image->dir.'/landscape_'.$image->name, ['alt' => $link->name, 'class' => 'img-responsive'])?>
                    <?=  $this->Html->link('<i class="fa fa-close"></i>', '/admin/link_images/delete/'.$image->id, ['class' => '', 'escape' => false]); ?>
                    <?php //echo $this->Html->link('<i class="fa fa-close"></i>', '/properties/view/'.$link->id, ['class' => '', 'target' => '_blank']); ?>
                </div>
            </div>
        <?php endforeach; ?> 
        <?php
    }
    ?>
    

    <?php
    echo $this->Form->input('photo', ['type' => 'file', 'label' => 'Files to upload']);
    echo $this->Form->button('<i class="fa fa-sign-in"></i> Save', ['class' => ['btn', 'btn-md btn-success', 'btn-primary-corp'], 'escape' => false]);  
    ?>

<?= $this->Form->end() ?>
```

My View file:

```php
<?= $this->Form->create($link, ['type' => 'file', 'class' => 'form-horizontal form-label-left']) ?>

    <?php
    echo $this->Form->input('title', ['placeholder' => '']);
    echo $this->Form->input('address', ['placeholder' => '']);
    echo $this->Form->input('active', ['placeholder' => '', 'options' => [false => 'No', true => 'Yes']]);
    ?>

    <?php 
    if(isset($link->link_images)){
        foreach ($link->link_images as $key => $image): ?>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Image</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php echo $this->Html->image('linkimages/link_image/'.$image->dir.'/landscape_'.$image->name, ['alt' => $link->name, 'class' => 'img-responsive'])?>
                    <?=  $this->Html->link('<i class="fa fa-close"></i>', '/admin/link_images/delete/'.$image->id, ['class' => '', 'escape' => false]); ?>
                    <?php //echo $this->Html->link('<i class="fa fa-close"></i>', '/properties/view/'.$link->id, ['class' => '', 'target' => '_blank']); ?>
                </div>
            </div>
        <?php endforeach; ?> 
        <?php
    }
    ?>
    

    <?php
    echo $this->Form->input('photo', ['type' => 'file', 'label' => 'Files to upload']);
    echo $this->Form->button('<i class="fa fa-sign-in"></i> Save', ['class' => ['btn', 'btn-md btn-success', 'btn-primary-corp'], 'escape' => false]);  
    ?>

<?= $this->Form->end() ?>
```

My add Method:

```php
<?= $this->Form->create($link, ['type' => 'file', 'class' => 'form-horizontal form-label-left']) ?>

    <?php
    echo $this->Form->input('title', ['placeholder' => '']);
    echo $this->Form->input('address', ['placeholder' => '']);
    echo $this->Form->input('active', ['placeholder' => '', 'options' => [false => 'No', true => 'Yes']]);
    ?>

    <?php 
    if(isset($link->link_images)){
        foreach ($link->link_images as $key => $image): ?>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Image</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php echo $this->Html->image('linkimages/link_image/'.$image->dir.'/landscape_'.$image->name, ['alt' => $link->name, 'class' => 'img-responsive'])?>
                    <?=  $this->Html->link('<i class="fa fa-close"></i>', '/admin/link_images/delete/'.$image->id, ['class' => '', 'escape' => false]); ?>
                    <?php //echo $this->Html->link('<i class="fa fa-close"></i>', '/properties/view/'.$link->id, ['class' => '', 'target' => '_blank']); ?>
                </div>
            </div>
        <?php endforeach; ?> 
        <?php
    }
    ?>
    

    <?php
    echo $this->Form->input('photo', ['type' => 'file', 'label' => 'Files to upload']);
    echo $this->Form->button('<i class="fa fa-sign-in"></i> Save', ['class' => ['btn', 'btn-md btn-success', 'btn-primary-corp'], 'escape' => false]);  
    ?>

<?= $this->Form->end() ?>
```

My links table has a 'photo' and 'dir' field.

When I try to save I get the following error:

```
Warning (2): rename(,C:\webroot\img\links\photo\8bf5aa05-05a2-4627-8bc9-5ceeedccb09f\1.jpg): Invalid argument [ROOT\vendor\davidyell\proffer\src\Model\Behavior\ProfferBehavior.php, line 271]
File `` could not be copied.
Proffer\Exception\CannotUploadFileException
```

When I test this with a hasMany relationship the files upload correctly and the db is stored accordingly, so as discussed it seems that this is a small bug in the source.

Thank you in advance.

**Comment by spacebiscuit** [comment] 2017-07-25 06:19
I also get the same error when I create a hasOne relation ship between Links and LinkImages, but it works with hasMany.

**Comment by davidyell** [comment] 2017-07-25 09:00
I think you have a bad copy and paste somewhere, as your code blocks are all templates.

As I said on IRC, this is because the `$_FILES` array is not storing the uploaded file into `/tmp`. This is why `rename()` has an empty first parameter.

You can see on (line 135)[https://github.com/davidyell/CakePHP3-Proffer/blob/master/src/Model/Behavior/ProfferBehavior.php#L135] that it's looking for `tmp_name` which comes directly from the `$_FILES` array.

This leads me to think that it's actually a problem with PHP and your form, and not actually with the plugin. It's also worth noting your field label in your template says 'Files to upload', but you're only providing a single file upload field.

The other problem could well be that you're using Windows. Having not developed on Windows, it could be that the it populates the `$_FILES` array differently.

I'll have to setup a `hasOne` relationship and test how the plugin reacts. There is potentially a new test-case here.

**Comment by davidyell** [comment] 2017-07-25 09:48
Well I've managed to implement a `hasOne` and it worked fine. So I don't think it's a bug with the plugin.

https://github.com/davidyell/CakePHP3-Proffer-Example/commit/767cf72f7b42dce7d6046b9eb0dc53a6e4ea4cb9

**Comment by davidyell** [comment] 2017-07-25 11:26
I have run the test suite on Mac OS, Ubuntu and Windows 10. The test suite passes in all those systems.

Sorry, but I can only assume that you have an error in your code somewhere. If you could update your pastes with the relevant code, perhaps we can progress.

In light of this, I'm going to close this and I cannot reproduce it in any way.

**Closed by davidyell** 2017-07-25 11:26 UTC
Labels: question

**Comment by spacebiscuit** [comment] 2017-07-25 14:53
Thanks for the update, yes i had tried for a hasOne relationship and also unrelated flat storage in the parent model. Apologues for pasted code, like you said something went wrong.

I will try again later.

**Comment by spacebiscuit** [comment] 2017-07-25 18:17
Please see the updated code snippets in Post #1.

With the above I now no longer get the rename error first reported, the Links model saves but the LinkImages related Model does not save and no images are uploaded.

As mentioned previously, hasMany relations save so this would suggest that this is not related to my server config.

Any ideas? Thanks!

**Comment by spacebiscuit** [comment] 2017-07-25 18:36
Ok I got it - I need:

echo $this->Form->input('link_image', ['type' => 'file', 'label' => 'File to upload']);

At last :)
